source 'https://rubygems.org'
ruby "2.5.1"

gem 'sinatra'
gem 'mongoid'
gem 'puma'
gem 'json', '~> 2.6', '>= 2.6.3'
gem 'sinatra-websocket', '~> 0.3.1'
gem 'dotenv', '~> 2.7'
gem 'passenger', '~> 5.0', '>= 5.0.30'